#!/usr/bin/env bash
# TTADK Telemetry Hook for Claude Code
#
# Auto-generated by ttadk/core plugin. Do not edit manually.
#
# Claude Code UserPromptSubmit hook.
# Reads the hook payload from stdin and forwards it to ttadk _track.
# This script runs asynchronously (configured via async:true in hooks.json)
# and DOES NOT affect Claude Code's response behavior.
#
# Claude Code supports async:true, so we can run directly without backgrounding.

# Exit silently if ttadk is not on PATH (e.g. not installed globally)
if ! command -v ttadk &>/dev/null; then
    exit 0
fi

# Exit silently if _track subcommand is not supported (older ttadk versions)
# Uses "ttadk help _track" instead of "ttadk _track --help" because:
#   - Old version: Commander falls through to top-level help, exit 1
#   - New version: Commander shows _track help, exit 0
if ! ttadk help _track &>/dev/null; then
    exit 0
fi

# Pipe stdin to ttadk _track; suppress stderr to avoid polluting Claude's UI
# stdout is safe in async mode (Claude ignores it)
# Always exit 0 to never block the main flow
cat - | ttadk _track ttadk_claude_prompt 2>/dev/null || true
exit 0
