package apitest

import (
	"fmt"
	"regexp"
	"strconv"
	"strings"
)

// jsonPathInExprRE rewrites bare `$.x.y` shorthand into `jsonpath('$.x.y')`
// so generated assertions can use either explicit jsonpath(...) or compact paths.
var jsonPathInExprRE = regexp.MustCompile(`\$(?:\.[A-Za-z_*][\w*]*|\[[^\]]+\])+`)

// typeofNoParensRE rewrites `typeof X` into `typeof(X)` after JSONPath rewrite.
var typeofNoParensRE = regexp.MustCompile(`\btypeof\s+([A-Za-z_]\w*(?:\([^)]*\))?)`)

func preprocessAssertion(src string) string {
	out := jsonPathInExprRE.ReplaceAllStringFunc(src, func(m string) string {
		return fmt.Sprintf("jsonpath(%q)", m)
	})
	out = typeofNoParensRE.ReplaceAllString(out, "typeof($1)")
	return strings.TrimSpace(out)
}

// evaluateAssertion supports the assertion subset generated by api-test:
// jsonpath(...), len(...), typeof(...), status_code, scalar comparisons, contains, and in.
func evaluateAssertion(expression string, statusCode int, body any) AssertResult {
	processed := preprocessAssertion(expression)
	passed, actual, err := evaluateComparison(processed, statusCode, body)
	return AssertResult{
		Expression: expression,
		Passed:     passed,
		Actual:     actual,
		Err:        err,
	}
}

func evaluateAll(expressions []string, statusCode int, body any) []AssertResult {
	results := make([]AssertResult, 0, len(expressions))
	for _, e := range expressions {
		results = append(results, evaluateAssertion(e, statusCode, body))
	}
	return results
}

func evaluateComparison(expression string, statusCode int, body any) (bool, any, error) {
	lhs, op, rhs, ok := splitComparison(expression)
	if !ok {
		return false, nil, fmt.Errorf("unsupported assertion expression %q", expression)
	}

	left, err := evalOperand(lhs, statusCode, body)
	if err != nil {
		return false, nil, err
	}
	right, err := parseLiteral(rhs)
	if err != nil {
		right, err = evalOperand(rhs, statusCode, body)
		if err != nil {
			return false, left, err
		}
	}

	passed, err := compareValues(left, op, right)
	if err != nil {
		return false, left, err
	}
	return passed, left, nil
}

func splitComparison(expression string) (string, string, string, bool) {
	ops := []string{"contains", "in", "==", "!=", ">=", "<=", ">", "<"}
	for i := 0; i < len(expression); i++ {
		if insideStringOrCall(expression, i) {
			continue
		}
		for _, op := range ops {
			if !strings.HasPrefix(expression[i:], op) {
				continue
			}
			if op == "contains" && !wordBoundary(expression, i, len(op)) {
				continue
			}
			return strings.TrimSpace(expression[:i]), op, strings.TrimSpace(expression[i+len(op):]), true
		}
	}
	return "", "", "", false
}

func insideStringOrCall(s string, pos int) bool {
	quote := byte(0)
	depth := 0
	for i := 0; i < pos; i++ {
		ch := s[i]
		if quote != 0 {
			if ch == '\\' {
				i++
				continue
			}
			if ch == quote {
				quote = 0
			}
			continue
		}
		switch ch {
		case '\'', '"':
			quote = ch
		case '(':
			depth++
		case ')':
			if depth > 0 {
				depth--
			}
		}
	}
	return quote != 0 || depth > 0
}

func wordBoundary(s string, start, n int) bool {
	before := start == 0 || isSpace(s[start-1])
	afterIdx := start + n
	after := afterIdx >= len(s) || isSpace(s[afterIdx])
	return before && after
}

func isSpace(b byte) bool {
	return b == ' ' || b == '\t' || b == '\n' || b == '\r'
}

func evalOperand(src string, statusCode int, body any) (any, error) {
	src = strings.TrimSpace(src)
	if src == "status_code" {
		return statusCode, nil
	}
	if strings.HasPrefix(src, "len(") && strings.HasSuffix(src, ")") {
		v, err := evalOperand(src[len("len("):len(src)-1], statusCode, body)
		if err != nil {
			return nil, err
		}
		return exprLen(v), nil
	}
	if strings.HasPrefix(src, "typeof(") && strings.HasSuffix(src, ")") {
		v, err := evalOperand(src[len("typeof("):len(src)-1], statusCode, body)
		if err != nil {
			return nil, err
		}
		return typeofValue(v), nil
	}
	if path, ok := parseJSONPathCall(src); ok {
		v, exists := jsonPathExtract(body, path)
		if !exists {
			return nil, nil
		}
		return v, nil
	}
	if strings.HasPrefix(src, "$") {
		v, exists := jsonPathExtract(body, src)
		if !exists {
			return nil, nil
		}
		return v, nil
	}
	return parseLiteral(src)
}

func parseJSONPathCall(src string) (string, bool) {
	if !strings.HasPrefix(src, "jsonpath(") || !strings.HasSuffix(src, ")") {
		return "", false
	}
	inner := strings.TrimSpace(src[len("jsonpath(") : len(src)-1])
	if len(inner) < 2 {
		return "", false
	}
	if (inner[0] == '\'' || inner[0] == '"') && inner[len(inner)-1] == inner[0] {
		unquoted, err := strconv.Unquote(string(inner[0]) + inner[1:len(inner)-1] + string(inner[0]))
		if err == nil {
			return unquoted, true
		}
		return inner[1 : len(inner)-1], true
	}
	return "", false
}

func parseLiteral(src string) (any, error) {
	src = strings.TrimSpace(src)
	if strings.HasPrefix(src, "[") && strings.HasSuffix(src, "]") {
		return parseListLiteral(src)
	}
	if src == "null" {
		return nil, nil
	}
	if src == "true" {
		return true, nil
	}
	if src == "false" {
		return false, nil
	}
	if len(src) >= 2 && (src[0] == '\'' || src[0] == '"') && src[len(src)-1] == src[0] {
		if src[0] == '\'' {
			return strings.ReplaceAll(src[1:len(src)-1], `\'`, `'`), nil
		}
		return strconv.Unquote(src)
	}
	if strings.ContainsAny(src, ".eE") {
		if f, err := strconv.ParseFloat(src, 64); err == nil {
			return f, nil
		}
	}
	if i, err := strconv.ParseInt(src, 10, 64); err == nil {
		return i, nil
	}
	return nil, fmt.Errorf("unsupported literal %q", src)
}

func parseListLiteral(src string) ([]any, error) {
	inner := strings.TrimSpace(src[1 : len(src)-1])
	if inner == "" {
		return []any{}, nil
	}
	parts := splitListItems(inner)
	out := make([]any, 0, len(parts))
	for _, part := range parts {
		v, err := parseLiteral(part)
		if err != nil {
			return nil, err
		}
		out = append(out, v)
	}
	return out, nil
}

func splitListItems(src string) []string {
	parts := make([]string, 0, 4)
	start := 0
	quote := byte(0)
	for i := 0; i < len(src); i++ {
		ch := src[i]
		if quote != 0 {
			if ch == '\\' {
				i++
				continue
			}
			if ch == quote {
				quote = 0
			}
			continue
		}
		if ch == '\'' || ch == '"' {
			quote = ch
			continue
		}
		if ch == ',' {
			parts = append(parts, strings.TrimSpace(src[start:i]))
			start = i + 1
		}
	}
	parts = append(parts, strings.TrimSpace(src[start:]))
	return parts
}

func compareValues(left any, op string, right any) (bool, error) {
	if op == "in" {
		arr, ok := right.([]any)
		if !ok {
			return false, fmt.Errorf("operator 'in' expects list literal on RHS")
		}
		for _, item := range arr {
			if equalValues(left, item) {
				return true, nil
			}
		}
		return false, nil
	}
	if op == "contains" {
		return containsValue(left, right), nil
	}
	if lf, lok := asFloat(left); lok {
		if rf, rok := asFloat(right); rok {
			switch op {
			case "==":
				return lf == rf, nil
			case "!=":
				return lf != rf, nil
			case ">":
				return lf > rf, nil
			case ">=":
				return lf >= rf, nil
			case "<":
				return lf < rf, nil
			case "<=":
				return lf <= rf, nil
			}
		}
	}
	cmp := fmt.Sprint(left)
	rhs := fmt.Sprint(right)
	switch op {
	case "==":
		return equalValues(left, right), nil
	case "!=":
		return !equalValues(left, right), nil
	case ">":
		return cmp > rhs, nil
	case ">=":
		return cmp >= rhs, nil
	case "<":
		return cmp < rhs, nil
	case "<=":
		return cmp <= rhs, nil
	default:
		return false, fmt.Errorf("unsupported operator %q", op)
	}
}

func asFloat(v any) (float64, bool) {
	switch t := v.(type) {
	case int:
		return float64(t), true
	case int8:
		return float64(t), true
	case int16:
		return float64(t), true
	case int32:
		return float64(t), true
	case int64:
		return float64(t), true
	case uint:
		return float64(t), true
	case uint8:
		return float64(t), true
	case uint16:
		return float64(t), true
	case uint32:
		return float64(t), true
	case uint64:
		return float64(t), true
	case float32:
		return float64(t), true
	case float64:
		return t, true
	default:
		return 0, false
	}
}

func equalValues(left, right any) bool {
	if left == nil || right == nil {
		return left == nil && right == nil
	}
	if lf, lok := asFloat(left); lok {
		if rf, rok := asFloat(right); rok {
			return lf == rf
		}
	}
	return fmt.Sprint(left) == fmt.Sprint(right)
}

func containsValue(left, right any) bool {
	switch t := left.(type) {
	case string:
		return strings.Contains(t, fmt.Sprint(right))
	case []any:
		for _, item := range t {
			if equalValues(item, right) {
				return true
			}
		}
	}
	return false
}

// typeofValue returns a JSON-aligned type name. The canonical names are
// 'int' / 'float' / 'string' / 'boolean' / 'list' / 'dict' / 'null'.
func typeofValue(v any) string {
	if v == nil {
		return "null"
	}
	switch v.(type) {
	case bool:
		return "boolean"
	case int, int8, int16, int32, int64,
		uint, uint8, uint16, uint32, uint64:
		return "int"
	case float32:
		return "float"
	case float64:
		f := v.(float64)
		if f == float64(int64(f)) {
			return "int"
		}
		return "float"
	case string:
		return "string"
	case []any, []string, []int, []int64, []float64, []bool:
		return "list"
	case map[string]any, map[string]string:
		return "dict"
	default:
		return fmt.Sprintf("%T", v)
	}
}

func exprLen(v any) int {
	switch t := v.(type) {
	case nil:
		return 0
	case string:
		return len(t)
	case []any:
		return len(t)
	case map[string]any:
		return len(t)
	default:
		return 0
	}
}
