package apitest

import (
	"bytes"
	"encoding/json"
	"fmt"
	"strconv"
	"strings"
)

type jsonPathSegment struct {
	key      string
	index    int
	wildcard bool
	hasIndex bool
}

// jsonPathExtract evaluates the small JSONPath subset generated by api-test:
// `$`, `$.a.b`, `$.a[0].b`, `$[0]`, `$['a']`, and `$.a[*].b`.
func jsonPathExtract(data any, path string) (any, bool) {
	root, ok := normalizeJSONInput(data)
	if !ok {
		return nil, false
	}
	segments, ok := parseJSONPath(path)
	if !ok {
		return nil, false
	}
	if len(segments) == 0 {
		return root, true
	}

	nodes := []any{root}
	for _, segment := range segments {
		next := make([]any, 0)
		for _, node := range nodes {
			values := applyJSONPathSegment(node, segment)
			next = append(next, values...)
		}
		if len(next) == 0 {
			return nil, false
		}
		nodes = next
	}
	if len(nodes) == 1 {
		return nodes[0], true
	}
	return nodes, true
}

func normalizeJSONInput(data any) (any, bool) {
	switch v := data.(type) {
	case nil:
		return nil, false
	case string:
		var out any
		if err := decodeJSONUseNumber([]byte(v), &out); err != nil {
			return nil, false
		}
		return normalizeNumbers(out), true
	case []byte:
		var out any
		if err := decodeJSONUseNumber(v, &out); err != nil {
			return nil, false
		}
		return normalizeNumbers(out), true
	case json.RawMessage:
		var out any
		if err := decodeJSONUseNumber(v, &out); err != nil {
			return nil, false
		}
		return normalizeNumbers(out), true
	default:
		return normalizeNumbers(v), true
	}
}

func parseJSONPath(path string) ([]jsonPathSegment, bool) {
	path = strings.TrimSpace(path)
	if path == "$" {
		return nil, true
	}
	if path == "" || path[0] != '$' {
		return nil, false
	}
	path = path[1:]
	segments := make([]jsonPathSegment, 0)
	for len(path) > 0 {
		switch path[0] {
		case '.':
			path = path[1:]
			key, rest := readJSONPathKey(path)
			if key == "" {
				return nil, false
			}
			segments = append(segments, jsonPathSegment{key: key})
			path = rest
		case '[':
			inner, rest, ok := readBracket(path)
			if !ok {
				return nil, false
			}
			segment, ok := bracketSegment(inner)
			if !ok {
				return nil, false
			}
			segments = append(segments, segment)
			path = rest
		default:
			return nil, false
		}
	}
	return segments, true
}

func readJSONPathKey(path string) (string, string) {
	for i := 0; i < len(path); i++ {
		if path[i] == '.' || path[i] == '[' {
			return path[:i], path[i:]
		}
	}
	return path, ""
}

func readBracket(path string) (string, string, bool) {
	quote := byte(0)
	for i := 1; i < len(path); i++ {
		ch := path[i]
		if quote != 0 {
			if ch == '\\' {
				i++
				continue
			}
			if ch == quote {
				quote = 0
			}
			continue
		}
		if ch == '\'' || ch == '"' {
			quote = ch
			continue
		}
		if ch == ']' {
			return path[1:i], path[i+1:], true
		}
	}
	return "", "", false
}

func bracketSegment(inner string) (jsonPathSegment, bool) {
	inner = strings.TrimSpace(inner)
	if inner == "*" {
		return jsonPathSegment{wildcard: true}, true
	}
	if len(inner) >= 2 && (inner[0] == '\'' || inner[0] == '"') && inner[len(inner)-1] == inner[0] {
		key := inner[1 : len(inner)-1]
		return jsonPathSegment{key: key}, true
	}
	idx, err := strconv.Atoi(inner)
	if err != nil {
		return jsonPathSegment{}, false
	}
	return jsonPathSegment{index: idx, hasIndex: true}, true
}

func applyJSONPathSegment(node any, segment jsonPathSegment) []any {
	if segment.wildcard {
		switch v := node.(type) {
		case []any:
			return append([]any(nil), v...)
		case map[string]any:
			out := make([]any, 0, len(v))
			for _, item := range v {
				out = append(out, item)
			}
			return out
		default:
			return nil
		}
	}
	if segment.hasIndex {
		arr, ok := node.([]any)
		if !ok || segment.index < 0 || segment.index >= len(arr) {
			return nil
		}
		return []any{arr[segment.index]}
	}
	m, ok := node.(map[string]any)
	if !ok {
		return nil
	}
	value, ok := m[segment.key]
	if !ok {
		return nil
	}
	return []any{value}
}

func normalizeNumbers(v any) any {
	switch t := v.(type) {
	case map[string]any:
		for k, sub := range t {
			t[k] = normalizeNumbers(sub)
		}
		return t
	case []any:
		for i, sub := range t {
			t[i] = normalizeNumbers(sub)
		}
		return t
	case float64:
		if t == float64(int64(t)) {
			return int64(t)
		}
		return t
	case json.Number:
		if i, err := t.Int64(); err == nil {
			return i
		}
		if f, err := t.Float64(); err == nil {
			return f
		}
		return string(t)
	default:
		return v
	}
}

func decodeJSONUseNumber(data []byte, out any) error {
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.UseNumber()
	return decoder.Decode(out)
}

func jsonPathDebugValue(v any) string {
	b, err := json.Marshal(v)
	if err != nil {
		return fmt.Sprint(v)
	}
	return string(b)
}
